language: php

php:
  - 7.2
  - 7.3
  - 7.4

dist: xenial

services:
  - postgresql
  - mysql

env:
  matrix:
    - DB=mysql db_dsn='mysql://root@127.0.0.1/cakephp_test'
    - DB=pgsql db_dsn='postgres://postgres@127.0.0.1/cakephp_test'
    - DB=sqlite
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.3
      env: CHECKS=1 DEFAULT=0

  allow_failures:
    - php: 7.4

install:
  - composer install --prefer-dist --no-interaction

before_script:
  - if [[ $DB == 'mysql' ]]; then mysql -u root -e 'CREATE DATABASE cakephp_test;'; fi
  - if [[ $DB == 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi
  - if [[ $CHECKS == 1 ]]; then composer require --dev psalm/phar:^3.6; fi

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $CHECKS == 1 ]]; then vendor/bin/psalm.phar --show-info=false; fi
  - if [[ $CHECKS == 1 ]]; then vendor/bin/phpcs --colors --parallel=16 -p src/ tests/; fi

notifications:
  email: false
